# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-copilotdemojivane-dfgdgqbduabo6-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: GitHub Action for Yarn
        # You may pin to the exact commit or the version.
        uses: Borales/actions-yarn@v4.2.0
        with:
          # Yarn command
          cmd: |
              cd samples/apps/copilot-chat-app/webapp
              yarn
              yarn build
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: |
              cd samples/apps/copilot-chat-app/webapp
              yarn build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: front-app
          path: samples/apps/copilot-chat-app/webapp/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-copilotdemojivane-dfgdgqbduabo6-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_33809D32B78540C4B54A880357C2B3CD }}
          package: .
